-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    salt character(10) NOT NULL,
    password_hash character(256) NOT NULL,
    PRIMARY KEY (id)
);
END;
