-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    salt bytea NOT NULL,
    password_hash bytea NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT c_unique_user_email UNIQUE (email)
);
END;
